/*
 * This file is generated by jOOQ.
 */
package tf.sailor.pixivdl.db.tables.records;


import javax.annotation.Nullable;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import tf.sailor.pixivdl.db.tables.PixivUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PixivUserRecord extends UpdatableRecordImpl<PixivUserRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 570028700;

    /**
     * Setter for <code>public.pixiv_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pixiv_user.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pixiv_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pixiv_user.username</code>.
     */
    @NotNull
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pixiv_user.display_name</code>.
     */
    public void setDisplayName(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pixiv_user.display_name</code>.
     */
    @Nullable
    public String getDisplayName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PixivUser.PIXIV_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return PixivUser.PIXIV_USER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return PixivUser.PIXIV_USER.DISPLAY_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    @Nullable
    public String component3() {
        return getDisplayName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    @Nullable
    public String value3() {
        return getDisplayName();
    }

    @Override
    public PixivUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PixivUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public PixivUserRecord value3(@Nullable String value) {
        setDisplayName(value);
        return this;
    }

    @Override
    public PixivUserRecord values(Integer value1, String value2, @Nullable String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PixivUserRecord
     */
    public PixivUserRecord() {
        super(PixivUser.PIXIV_USER);
    }

    /**
     * Create a detached, initialised PixivUserRecord
     */
    public PixivUserRecord(Integer id, String username, @Nullable String displayName) {
        super(PixivUser.PIXIV_USER);

        set(0, id);
        set(1, username);
        set(2, displayName);
    }
}
