/*
 * This file is generated by jOOQ.
 */
package tf.sailor.pixivdl.db.tables.records;


import javax.annotation.Nullable;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import tf.sailor.pixivdl.db.tables.Tag;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRecord extends UpdatableRecordImpl<TagRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -147373207;

    /**
     * Setter for <code>public.tag.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tag.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tag.original_name</code>.
     */
    public void setOriginalName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tag.original_name</code>.
     */
    @NotNull
    public String getOriginalName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tag.translated_name</code>.
     */
    public void setTranslatedName(@Nullable String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tag.translated_name</code>.
     */
    @Nullable
    public String getTranslatedName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tag.TAG.ID;
    }

    @Override
    public Field<String> field2() {
        return Tag.TAG.ORIGINAL_NAME;
    }

    @Override
    public Field<String> field3() {
        return Tag.TAG.TRANSLATED_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getOriginalName();
    }

    @Override
    @Nullable
    public String component3() {
        return getTranslatedName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getOriginalName();
    }

    @Override
    @Nullable
    public String value3() {
        return getTranslatedName();
    }

    @Override
    public TagRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TagRecord value2(String value) {
        setOriginalName(value);
        return this;
    }

    @Override
    public TagRecord value3(@Nullable String value) {
        setTranslatedName(value);
        return this;
    }

    @Override
    public TagRecord values(Integer value1, String value2, @Nullable String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagRecord
     */
    public TagRecord() {
        super(Tag.TAG);
    }

    /**
     * Create a detached, initialised TagRecord
     */
    public TagRecord(Integer id, String originalName, @Nullable String translatedName) {
        super(Tag.TAG);

        set(0, id);
        set(1, originalName);
        set(2, translatedName);
    }
}
