/*
 * This file is generated by jOOQ.
 */
package tf.sailor.pixivdl.db;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import tf.sailor.pixivdl.db.tables.Artwork;
import tf.sailor.pixivdl.db.tables.ArtworkTag;
import tf.sailor.pixivdl.db.tables.Bookmark;
import tf.sailor.pixivdl.db.tables.Tag;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_ARTWORK_BOOKMARKS = Indexes0.IDX_ARTWORK_BOOKMARKS;
    public static final Index IDX_ARTWORK_CAPTION = Indexes0.IDX_ARTWORK_CAPTION;
    public static final Index IDX_ARTWORK_LEWD_LEVEL = Indexes0.IDX_ARTWORK_LEWD_LEVEL;
    public static final Index IDX_ARTWORK_R18 = Indexes0.IDX_ARTWORK_R18;
    public static final Index IDX_ARTWORK_TITLE = Indexes0.IDX_ARTWORK_TITLE;
    public static final Index IDX_ARTWORK_UPLOADED_AT = Indexes0.IDX_ARTWORK_UPLOADED_AT;
    public static final Index IDX_ARTWORK_VIEWS = Indexes0.IDX_ARTWORK_VIEWS;
    public static final Index FKEY_ARTWORK_TAG_ARTWORK_IDX = Indexes0.FKEY_ARTWORK_TAG_ARTWORK_IDX;
    public static final Index FKEY_ARTWORK_TAG_TAG_ID = Indexes0.FKEY_ARTWORK_TAG_TAG_ID;
    public static final Index IDX_BOOKMARK_IS_PRIVATE = Indexes0.IDX_BOOKMARK_IS_PRIVATE;
    public static final Index IDX_TAG_TRANSLATED_NAME = Indexes0.IDX_TAG_TRANSLATED_NAME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index IDX_ARTWORK_BOOKMARKS = Internal.createIndex("idx_artwork_bookmarks", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.TOTAL_BOOKMARKS }, false);
        public static Index IDX_ARTWORK_CAPTION = Internal.createIndex("idx_artwork_caption", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.CAPTION }, false);
        public static Index IDX_ARTWORK_LEWD_LEVEL = Internal.createIndex("idx_artwork_lewd_level", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.LEWD_LEVEL }, false);
        public static Index IDX_ARTWORK_R18 = Internal.createIndex("idx_artwork_r18", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.R18 }, false);
        public static Index IDX_ARTWORK_TITLE = Internal.createIndex("idx_artwork_title", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.TITLE }, false);
        public static Index IDX_ARTWORK_UPLOADED_AT = Internal.createIndex("idx_artwork_uploaded_at", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.UPLOADED_AT }, false);
        public static Index IDX_ARTWORK_VIEWS = Internal.createIndex("idx_artwork_views", Artwork.ARTWORK, new OrderField[] { Artwork.ARTWORK.TOTAL_VIEWS }, false);
        public static Index FKEY_ARTWORK_TAG_ARTWORK_IDX = Internal.createIndex("fkey_artwork_tag_artwork_idx", ArtworkTag.ARTWORK_TAG, new OrderField[] { ArtworkTag.ARTWORK_TAG.ARTWORK_ID }, false);
        public static Index FKEY_ARTWORK_TAG_TAG_ID = Internal.createIndex("fkey_artwork_tag_tag_id", ArtworkTag.ARTWORK_TAG, new OrderField[] { ArtworkTag.ARTWORK_TAG.TAG_ID }, false);
        public static Index IDX_BOOKMARK_IS_PRIVATE = Internal.createIndex("idx_bookmark_is_private", Bookmark.BOOKMARK, new OrderField[] { Bookmark.BOOKMARK.ARTWORK_ID }, false);
        public static Index IDX_TAG_TRANSLATED_NAME = Internal.createIndex("idx_tag_translated_name", Tag.TAG, new OrderField[] { Tag.TAG.TRANSLATED_NAME }, false);
    }
}
