/*
 * This file is generated by jOOQ.
 */
package tf.sailor.pixivdl.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.pixiv_login_id_seq</code>
     */
    public static final Sequence<Integer> PIXIV_LOGIN_ID_SEQ = Internal.createSequence("pixiv_login_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.tag_id_seq</code>
     */
    public static final Sequence<Integer> TAG_ID_SEQ = Internal.createSequence("tag_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
