/*
 * This file is generated by jOOQ.
 */
package tf.sailor.pixivdl.db;


import tf.sailor.pixivdl.db.tables.Artwork;
import tf.sailor.pixivdl.db.tables.ArtworkTag;
import tf.sailor.pixivdl.db.tables.Bookmark;
import tf.sailor.pixivdl.db.tables.PixivLogin;
import tf.sailor.pixivdl.db.tables.PixivUser;
import tf.sailor.pixivdl.db.tables.Tag;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.artwork</code>.
     */
    public static final Artwork ARTWORK = Artwork.ARTWORK;

    /**
     * The table <code>public.artwork_tag</code>.
     */
    public static final ArtworkTag ARTWORK_TAG = ArtworkTag.ARTWORK_TAG;

    /**
     * The table <code>public.bookmark</code>.
     */
    public static final Bookmark BOOKMARK = Bookmark.BOOKMARK;

    /**
     * The table <code>public.pixiv_login</code>.
     */
    public static final PixivLogin PIXIV_LOGIN = PixivLogin.PIXIV_LOGIN;

    /**
     * The table <code>public.pixiv_user</code>.
     */
    public static final PixivUser PIXIV_USER = PixivUser.PIXIV_USER;

    /**
     * The table <code>public.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;
}
